### ISSUE TITLE
初期画面のデザイン (2)

### ISSUE THREAD

**Issue by hytkgami** [RHD-Winter-Intern-teamF2016/peQuAry#10]
## WHY

#6  

初期画面：ユーザー（客）が最初に目にする画面，初期タグを表示

## WHAT
- [x] ページタイトル，アイキャッチ的な

- 何を食べるか決められない時に刺さる言葉，タイトルは？

- [x] 表示されるタグの内容

- カテゴリで分けずバラバラなタグを表示

- [x] 表示されるタグの配置

- グリッド状　〇　or　×

- タグの個数　固定　or　変動

  - 具体的な個数　？

**Comment by Maccha-Latte** [comment]
めちゃくちゃシンプルなモックを作成
