### ISSUE TITLE
キーワードのグルーピング

### ISSUE THREAD

**Issue by hytkgami** [RHD-Winter-Intern-teamF2016/peQuAry#37]
|キーワード|矛盾するカテゴリ|
|:--:|:--:|
|専門店|なし|
|男飯|軽め|
|スペイン料理|なし|
|庶民派|高級|
|たんぱく|なし|
|肉|軽め|
|しゃぶしゃぶ|軽め|
|軽め|がっつり|
|濃厚|軽め|
|重め|軽め|
|わいわい|なし|
|定食|なし|
|食べ放題|軽め|
|スイーツ|がっつり|
|海鮮料理|なし|
|少人数|大人数|
|甘い|がっつり|
|フレンチ|なし|
|日本酒|なし|
|レストラン|なし|
|がっつり|軽め|
|あっさり|がっつり|
|カレー|軽め|
|カフェ|がっつり|
|中華|軽め|
|パーティー|少人数|
|スタミナ|軽め|
|カツ丼|軽め|
|麺|なし|
|野菜|がっつり|
|明るい|なし|
|珍しい|なし|
|社会人|なし|
|激辛|軽め|
|広い|なし|
|こってり|軽め|
|小・中学生|なし|
|分煙|なし|
|ブルジョア|リーズナブル|
|北京ダック|軽め|
|つまみ|がっつり|
|洋食|なし|
|一軒目|なし|
|夜景がキレイ|なし|
|多ジャンル|なし|
|ワイン充実|なし|
|喫煙|なし|
|辛い|なし|
|早い|なし|
|串焼き|軽め|
|打ち上げ|なし|
|非チェーン|なし|
|飲み放題|なし|
|女子|なし|
|学生|なし|
|創作料理|リーズナブル, 軽め|
|和食|なし|
|ビュッフェ|軽め|
|郷土料理|軽め|
|健康|なし|
|おかわり自由|軽め|
|チェーン|高級|
|安い|高級|
|はしご|なし|
|暗め|なし|
|米|軽め|
|飲む|なし|
|飲まない|なし|
|イタリアン|なし|
|個室|リーズナブル|
|静か|なし|

**Comment by hytkgami** [comment]
@mab37 
@jianghan0 
@Maccha-Latte 

グルーピングしてみたけど漏れとかあるかもなので
確認お願いします〜〜〜〜

**Comment by jianghan0** [comment]
食べ放題：軽め
チェーン：高級

はどうかな

**Comment by hytkgami** [comment]
@jianghan0 
ありがとう！
ってことは**飲み放題**もカテゴリ**軽め**と矛盾するね

**Comment by hytkgami** [comment]
@jianghan0 
変更しました！

**Comment by Maccha-Latte** [comment]
いいと思う！

**Comment by hytkgami** [comment]
@Maccha-Latte 
Thx!

**Comment by hytkgami** [comment]
- [ ] Seedファイルをつくる
