### ISSUE TITLE
初期のタグデータとして用いるレビューのスクレイピング (8)

### ISSUE THREAD

**Issue by hytkgami** [RHD-Winter-Intern-teamF2016/peQuAry#7]
## WHY

#1 
ホットペッパーグルメや食べログなどのレビューをもとに、
直感的なタグで食事を表現したい。

## WHAT

- [x] 初期のタグデータとして用いるレビューのスクレイピング
  - [x] スクレイピングしたレビューと初期タグのマッチングからタグ決定
  - [x] 初期の店舗リストデータを作るためのホットペッパーグルメAPIのスクレイピング

**Comment by mab37** [comment]
# スクレイピング手順

* Hotpepper APIの検索クエリでCount,Startを変更して対象店舗すべての店舗IDを引っ張ってくる
* 店舗IDからレビューのあるURLが定まるので、そのページの中身からnokogiri等でレビュー抽出
* レビュー内でタグに一致する部分をカウントして、その結果をshop_tagsテーブルに追加する
